### ISSUE TITLE
TCP example is incorrect

### ISSUE THREAD

**Issue by Sorc96** [valiot/modbux#11]
I have been learning about modbus and ran into a problem with the TCP example in this package..

In the TCP example for the client, the option `port` is passed, but the correct option is `tcp_port`. This leads to `econnrefused` and it took me a while to realize what the problem was.

Also, the client is started as `active`, but then `confirmation/1` if used to get the value, which does not work. Changing `active` to `false` fixes this. It would be nice to have an example for an `active` client as well.

**Comment by alde103** [comment]
Fixed on #061c67 commit. Thanks
